[build]
  base = "ui"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "models/*"
    [headers.values]
    access-control-allow-origin = "https://autoyeai.com"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    content-security-policy = "script-src autoyeai.com *.autoyeai.com; base-uri * 'self'; worker-src *.autoyeai.com blob: ;"
    content-type = "text/html; charset=utf-8"
    content-encoding = "gzip"
